# Generated by Django 4.0.5 on 2022-09-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(default='10hrs', max_length=20),
        ),
    ]
